### ISSUE TITLE
multiple scm issue in one job

### ISSUE THREAD

**Issue by widgetpl** [nishio-dens/bitbucket-pullrequest-builder-plugin#92]
I faced an issu using BB PR plugin with multiple SCMs configuration. I have job with two SCMs, one for BB PR plugin and another one for acceptance tests. I am using `basedir` in git scm to separate directories for each repo. Repository for BB PR plugin is using environment variables for branches `sourceBranch` and `targetBranch` and secon scm has hardcoded branch. When job is triggered my second scm is trying to pull branch/revision from first scm which is failing.
Hope i have described my issue quite clearly. I am using jenkins job builder to configure jobs and it looks like:

```
scm:
      - git:
          url: 'git@bitbucket.org:${{repositoryOwner}}/${{repositoryName}}.git'
          credentials-id: 430e72d0-c894-4aa2-8284-bde264d94ee9
          branches:
            - '*/${{sourceBranch}}'
          browser: bitbucketweb
          browser-url: 'https://bitbucket.org/${{repositoryOwner}}/${{repositoryName}}'
          basedir: dir1
          timeout: 5
          wipe-workspace: false
          clean:
            before: true
          skip-tag: true
          merge:
            remote: 'origin'
            branch: ${{targetBranch}}
            strategy: 'default'
            fast-forward-mode: 'FF'
      - git:
          url: '{obj:repo_tests}'
          credentials-id: 430e72d0-c894-4aa2-8284-bde264d94ee9
          branches:
            - 'ConfigModification'
          browser: bitbucketweb
          browser-url: '{url_tests}'
          basedir: dir2
          timeout: 5
          wipe-workspace: false
          clean:
            before: true
          skip-tag: true
```
